version: '3.8'

services:
  # 主应用
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SCHEDULER_TYPE=cron
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  # 定时任务容器
  scheduler:
    build: .
    command: |
      sh -c "
        echo '*/10 * * * * node scripts/cleanup-rooms.js' | crontab - &&
        crond -f
      "
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - app
